pipeline {
    agent any

    environment {
        KUBECTL = "kubectl"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }


    stages {
        stage("Build Docker Image") {
            steps {
            dir('GatewayService') {
                sh """
                    mvn clean install -DskipTests=true
                    docker build -t gateway-service:\$IMAGE_TAG .
                    docker save gateway-service:\$IMAGE_TAG | docker exec -i minikube docker load

                """
                }
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
            dir('GatewayService') {
                sh """
                    sed "s/TAG_PLACEHOLDER/\$IMAGE_TAG/" deployment.yml > deployment-with-image.yml
                    \$KUBECTL apply -f deployment-with-image.yml
                    \$KUBECTL apply -f service.yml

                """
                }
            }
        }
    }
}
