pipeline {
    agent any



    environment {
        KUBECTL = "kubectl"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage("Build Docker Image") {
            steps {
                sh """
                    mvn clean install -DskipTests=true
                    mvn test
                    docker build -t geolocation-service:\$IMAGE_TAG .

                    # Save and load image into Minikube
                    docker save geolocation-service:\$IMAGE_TAG | docker exec -i minikube docker load
                """
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
                sh """
                    sed "s/TAG_PLACEHOLDER/\$IMAGE_TAG/" deployment.yml > deployment-with-image.yml
                    \$KUBECTL apply -f deployment-with-image.yml
                    \$KUBECTL apply -f service.yml
                """
            }
        }
    }
}