package org.example.ticketmanagementservice.dtos;

import org.example.ticketmanagementservice.entities.enums.PaymentMethod;

import java.math.BigDecimal;
import java.util.UUID;

public record TicketPurchaseRequestDTO(
        UUID userId,
        UUID routeId,
        UUID startStopId,
        UUID endStopId,
        BigDecimal price,
        PaymentMethod paymentMethod,
        String idempotencyKey       // unique key generated by the caller
) {}