openapi: 3.0.3
info:
  title: Ticket Management Payment API
  description: API for processing ticket purchases and subscription purchases using Stripe
  version: 1.0.0
  contact:
    name: Ticket Management Service
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Payments
    description: Payment processing operations

paths:
  /api/v1/payments/ticket-purchase:
    post:
      tags:
        - Payments
      summary: Process ticket purchase payment
      description: Process a payment for ticket purchase using Stripe API
      operationId: processTicketPurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketPurchaseRequest'
      responses:
        '200':
          description: Payment + Ticket returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketPurchaseResponse'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error - Payment processing failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/payments/subscription-purchase:
    post:
      tags:
        - Payments
      summary: Process subscription purchase payment
      description: Process a payment for subscription purchase using Stripe API
      operationId: processSubscriptionPurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPurchaseRequest'
      responses:
        '200':
          description: Payment processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error - Payment processing failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/payments/{paymentId}:
    get:
      tags:
        - Payments
      summary: Get payment by ID
      description: Retrieve payment details by payment ID
      operationId: getPaymentById
      parameters:
        - name: paymentId
          in: path
          required: true
          description: Unique identifier of the payment
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Payment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/payments/transaction/{transactionId}:
    get:
      tags:
        - Payments
      summary: Get payment by transaction ID
      description: Retrieve payment details by Stripe transaction ID
      operationId: getPaymentByTransactionId
      parameters:
        - name: transactionId
          in: path
          required: true
          description: Stripe transaction ID
          schema:
            type: string
      responses:
        '200':
          description: Payment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:

    TicketPurchaseRequest:
      type: object
      required:
        - userId
        - busId
        - startStopId
        - endStopId
        - price
        - method
      properties:
        userId:
          type: string
          format: uuid
        busId:
          type: string
          format: uuid
        startStopId:
          type: string
          format: uuid
        endStopId:
          type: string
          format: uuid
        price:
          type: number
          format: decimal
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        idempotencyKey:
          type: string
        paymentMethodId:
          type: string

    SubscriptionPurchaseRequest:
      type: object
      required:
        - userId
        - subscriptionId
        - price
        - method
      properties:
        userId:
          type: string
          format: uuid
        subscriptionId:
          type: string
          format: uuid
        price:
          type: number
          format: decimal
        method:
          $ref: '#/components/schemas/PaymentMethod'
        idempotencyKey:
          type: string
        paymentMethodId:
          type: string

    PaymentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        relatedId:
          type: string
          format: uuid
        price:
          type: number
          format: decimal
        method:
          $ref: '#/components/schemas/PaymentMethod'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        transactionId:
          type: string
        paymentDate:
          type: string
          format: date-time

    # NEW
    TicketPurchaseResponse:
      type: object
      properties:
        payment:
          $ref: '#/components/schemas/PaymentResponse'
        ticket:
          $ref: '#/components/schemas/TicketResponse'

    # NEW
    TicketResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        busId:
          type: string
          format: uuid
        startStopId:
          type: string
          format: uuid
        endStopId:
          type: string
          format: uuid
        price:
          type: number
        status:
          type: string
        purchaseDate:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
        validatedAt:
          type: string
          format: date-time
          nullable: true
        qrCode:
          type: string
          nullable: true
        paymentId:
          type: string
          format: uuid

    PaymentMethod:
      type: string
      enum:
        - CREDIT_CARD
        - DEBIT_CARD
        - PAYPAL
        - MOBILE_MONEY

    PaymentStatus:
      type: string
      enum:
        - PENDING
        - COMPLETED
        - FAILED
        - REFUNDED

    ErrorResponse:
      type: object
      required:
        - message
        - status
        - path
      properties:
        message:
          type: string
        status:
          type: integer
        path:
          type: string
