spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri : http://localhost:8081
          predicates:
            - Path=/api/v1/
        - id: routeService
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/
        - id: ticket
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/
        - id: user-subscriptions
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/user-subscription/**
          filters:
            - name: JwtAuthFilter
              args:
                role: PASSENGER
        - id: managing-subscriptions
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - name: JwtAuthFilter
              args:
                role: MANAGER
