spring:
  cloud:
    gateway:
      routes:
        - id: authentification
          uri : http://localhost:8081
          predicates:
            - Path=/api/v1/
        - id: buses
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/bus/**
        - id: read-routes
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/routes
            - Path=/api/v1/routes/{routeId}


        - id: manage-routes
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/routes
              Method=POST
            - Path=/api/v1/routes/{routeId}
              Method=PUT
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER

        - id: add-bus-to-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/routes/{routeId}/add-bus
              Method=POST
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER
        - id: read-stops
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stops
            - Path=/api/v1/stops/{stopId}

        - id: add-stop
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stops
              Method=POST
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER

        - id: update-stop
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stops/{stopId}
              Method=PUT
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER

        - id: read-route-stops
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/route-stops/{routeStopId}

        - id: update-route-stop
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/route-stops/{stopId}
              Method=PUT
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER

        - id: ticket
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/tickets/**
            - Path=/

        - id: user-subscriptions
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/user-subscription/**
          filters:
            - name: JwtAuthFilter
              args:
                roles: PASSENGER
        - id: managing-subscriptions
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - name: JwtAuthFilter
              args:
                roles: MANAGER
