pipeline {
    agent any



    environment {
        KUBECTL = "kubectl"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }


    stages {

        stage("Build Docker Image") {

            steps {
            dir('authenticationService') {
                sh """
                    mvn clean install -DskipTests=true
                    docker build -t auth-service:\$IMAGE_TAG .
                    docker save auth-service:\$IMAGE_TAG | docker exec -i minikube docker load
                """
                }
            }
        }

        stage("Deploy to Kubernetes") {


            steps {
            dir("authenticationService"){
                sh """
                    sed "s/TAG_PLACEHOLDER/\$IMAGE_TAG/" deployment.yml > deployment-with-image.yml
                    \$KUBECTL apply -f deployment-with-image.yml
                    \$KUBECTL apply -f service.yml

                """
                }
            }
        }
    }
}
